name: Test

on: 
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  tests:
    name: Node ${{ matrix.node }} build & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18', '20' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test
