name: Test

on: 
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  shellcheck:
    runs-on: [ubuntu-latest]
    container: 'docker://koalaman/shellcheck-alpine'
    steps:
      - uses: actions/checkout@v3
      - run: './scripts/lint-shell.sh'

  tests:
    name: Node ${{ matrix.node }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '18', '20' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run test
      - run: npm run eslint
